title:              Yuanping's Website
email:              yd346@cornell.edu
description:        A website for ORIR5270 Big Data Technologies
author:             Yuanping Du
baseurl:            ""
url:                "https://Yuanping919.github.io"

# Social Profiles
twitter_username:    
github_username:    Yuanping919
facebook_username:  Jason Powder
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
